version: "3.9"
services:
  backend:
    build: ./service/backend/
    ports:
      - "3001:3001"

  frontend:
    build: ./service/frontend
    ports:
      - "3000:3000"

  nginx:
    build: ./service/nginx
    ports:
      - 80:80

  mariadb:
    image: 'mariadb:10'
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: main_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb: