version: "3.9"
services:
  backend:
    build: ./service/backend/
    ports:
      - "3001:3001"

  frontend:
    build: ./service/frontend
    ports:
      - "3000:3000"

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./service/nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./service/nginx/user_conf.d:/etc/nginx/user_conf.d

  mariadb:
    image: 'mariadb:10'
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: main_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/:/var/lib/mysql

volumes:
  nginx_secrets:
      - mariadb:/var/lib/mysql
  mariadb:
  
