version: "3.9"
services:
  backend:
    build: ./service/backend/
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    networks:
      - back
      - default
    environment:
      DECODE: sfvmndxvnu1gi6jjdumaivvkj2ok6kzrdv6yap9r3el6jy45fb9dhuo5flleudig

  frontend:
    build: ./service/frontend
    ports:
      - "3000:3000"
    networks:
      - default

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./service/nginx/nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./service/nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - back
      - outside
      - default

  mariadb:
    image: 'mariadb:10'
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: e92]sPW6FXhZ5y_)
    ports:
      - "3306:3306"
    volumes:
      - mariadb_new:/var/lib/mysql
    networks:
      - back

volumes:
  nginx_secrets:
  mariadb_new:

networks:
  outside:
    external: true
  back: