version: "3.9"
services:
  backend:
    build: ./service/backend/
    networks:
      - backend
  frontend:
    build: ./service/frontend
    networks:
      - backend

  nginx:
    build: ./service/nginx
    ports:
      - "80:80"
    networks:
      - wan
      - backend

  mariadb:
    image: 'mariadb:10'
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: main_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend
      - wan

volumes:
  mariadb:

networks:
  backend:
    name: backend
    external: true
  wan:
    name: wan
    external: true