openapi: 3.0.0
tags:
  - Agenda
description: Get an agenda for the day given

parameters:
  - name: time
    in: query
    type: integer
    required: true
    description: time goes from 0 to 6 where 0 is monday and 6 is sunday
  - name: lat
    in: query
    type: number
    required: true
    description: latitude of the user
  - name: long
    in: query
    type: number
    required: true
    description: longitude of the user
  - name: r
    in: query
    type: integer
    required: true
    description: max distance from the user
  - name: hist
    in: header
    type: string
    required: true
    description: a jwt token encoded with the HS256 algorithm
  
responses:
    '200':
      description: Successful response
      schema: 
        $ref: '#definitions/Agenda'
    '300':
      description: Agenda contains empty spaces
definitions:
  ResponseAgenda:
    type: object
    properties:
      agenda:
        type: object
        schema:
          $ref: '#/Definitions/Agenda'
      hist:
        type: string
  Agenda:
    type: array
    items: 
      $ref: '#/definitions/Activity'
  Activity:
    type: object
    properties: 
      name:
        type: string
      adress:
        type: string
      categorie:
        type: string