openapi: 3.0.0
tags:
  - name: 
get:

  description: None
responses:
    '200':
      description: Successful response
      schema: 
        $ref: '#definitions/Text'
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
definitions:
  Text:
    type: object
    properties: 
      bonjour:
        type: string